# load packages----
library(rhdf5) #provides functions for handling hdf5 file formats (kallisto outputs bootstraps in this format)
library(tidyverse) # provides access to Hadley Wickham's collection of R packages for data science, which we will use throughout the course
library(tximport) # package for getting Kallisto results into R
library(ensembldb) #helps deal with ensembl
#library(BSgenome.Dmelanogaster.UCSC.dm6) #replace with your organism-specific database package
library(datapasta)
library(tibble)
library(edgeR)
library(matrixStats) # let's us easily calculate stats on rows or columns of a data matrix
library(cowplot) # allows you to combine multiple plots in one figure
library(corrplot)
library(DT) # for making interactive tables
library(plotly) # for making interactive plots
library(gt) # A layered 'grammar of tables' - think ggplot, but for tables
library(limma) # venerable package for differential gene expression using linear modeling
library(VennDiagram)

sampleID_2023 <- c("F3", "F5", "F6", "F7", "F8", 
               "M3", "M4", "M5", "M6")

sampleID_2022 <- c("DmF11", "DmF12", "DmF13", "DmF14", "DmF15", "DmF16",
                   "DmM20", "DmM21", "DmM22", "DmM23", "DmM24", "DmM25")

sampleID_2021 <- c("Dm_F10", "Dm_F5", "Dm_F6", "Dm_F8", "Dm_F9",
                   "Dm_M12", "Dm_M13", "Dm_M15", "Dm_M17")

sex_2023 <- c("F", "F", "F", "F", "F", 
       "M", "M", "M", "M")

sex_2022 <- c("F", "F", "F", "F", "F", "F",
              "M", "M", "M", "M", "M", "M")

sex_2021 <- c("F", "F", "F", "F", "F",
              "M", "M", "M", "M")

year_2023 <- c("2023", "2023", "2023", "2023", "2023", 
           "2023", "2023", "2023", "2023")

year_2022 <- c("2022", "2022", "2022", "2022", "2022", "2022", 
               "2022", "2022", "2022", "2022", "2022", "2022")

year_2021 <- c("2021", "2021", "2021", "2021", "2021",
               "2021", "2021", "2021", "2021")

df_2023 <- data.frame(factor(sampleID_2023), factor(sex_2023), factor(year_2023))
colnames(df_2023) <- c("sampleID", "sex", "year")

df_2022 <- data.frame(factor(sampleID_2022), factor(sex_2022), factor(year_2022))
colnames(df_2022) <- c("sampleID", "sex", "year")

df_2021 <- data.frame(factor(sampleID_2021), factor(sex_2021), factor(year_2021))
colnames(df_2021) <- c("sampleID", "sex", "year")

setwd("./Data/Raw")
# you can easily create file paths to the abundance files generated by Kallisto using the 'file.path' function
path_2023 <- file.path(df_2023$sample, "abundance.tsv") # set file paths to your mapped data
path_2022 <- file.path(df_2022$sample, "abundance.tsv") # set file paths to your mapped data
path_2021 <- file.path(df_2021$sample, "abundance.tsv") # set file paths to your mapped data

# now check to make sure this path is correct by seeing if the files exist
all(file.exists(path_2023)) 
all(file.exists(path_2021))
all(file.exists(path_2021)) 
# Fetch annotations using BiomaRt----

myMart <- useMart(biomart="ENSEMBL_MART_ENSEMBL")

#now grab the ensembl annotations
httr::set_config(httr::config(ssl_verifypeer = FALSE))
fly.anno <- useEnsembl(biomart="ENSEMBL_MART_ENSEMBL", dataset = "dmelanogaster_gene_ensembl",  mirror = "useast")
fly.filters <- listFilters(fly.anno)
fly.attributes <- listAttributes(fly.anno)

# Get transcript ID and gene mappings 
Tx.fly <- getBM(attributes=c('ensembl_transcript_id',
                             'external_gene_name'),
                mart = fly.anno)

Tx.fly <- as_tibble(Tx.fly)
#we need to rename the two columns we just retreived from biomart
Tx.fly <- Tx.fly %>% rename(target_id = ensembl_transcript_id, 
                            gene_name = external_gene_name)

colnames(Tx.fly) <- c("target_id", "gene_name")
Txi_gene_2023 <- tximport(path_2023, 
                     type = "kallisto", #type of alignment program
                     tx2gene = Tx.fly, # pulling genes from annotation mapping
                     txOut = FALSE, # If true, outputs transcripts data, if false, outputs gene level data
                     countsFromAbundance = "lengthScaledTPM",
                     ignoreTxVersion = TRUE)

saveRDS(Txi_gene_2023, file="2024_08/Txi_gene_2023.RData")


Txi_gene_2022 <- tximport(path_2022, 
                          type = "kallisto", #type of alignment program
                          tx2gene = Tx.fly, # pulling genes from annotation mapping
                          txOut = FALSE, # If true, outputs transcripts data, if false, outputs gene level data
                          countsFromAbundance = "lengthScaledTPM",
                          ignoreTxVersion = TRUE)

saveRDS(Txi_gene_2022, file="2024_08/Txi_gene_2022.RData")



Txi_gene_2021 <- tximport(path_2021, 
                          type = "kallisto", #type of alignment program
                          tx2gene = Tx.fly, # pulling genes from annotation mapping
                          txOut = FALSE, # If true, outputs transcripts data, if false, outputs gene level data
                          countsFromAbundance = "lengthScaledTPM",
                          ignoreTxVersion = TRUE)

saveRDS(Txi_gene_2021, file="2024_08/Txi_gene_2021.RData")

#2023

myCounts_2023 <- Txi_gene_2023$counts
myDGEList_2023 <- DGEList(counts=myCounts_2023, group = factor(sex_2023))
cpm <- cpm(myDGEList_2023) 
keepers <- rowSums(cpm>1)>=5
myDGEList_2023.filtered<- myDGEList_2023[keepers,]
myDGEList_2023.filtered.norm <- calcNormFactors(myDGEList_2023.filtered, method = "TMM")


group_2023 <- factor(c("F", "F", "F", "F", "F", 
                  "M", "M", "M", "M"))

design_2023 <- model.matrix(~0 + group_2023)
colnames(design_2023) <- gsub("group_2023", "", colnames(design_2023))
v.DEGList_2023.filtered.norm <- voom(myDGEList_2023.filtered.norm, design_2023, plot = TRUE)
fit_2023 <- lmFit(v.DEGList_2023.filtered.norm, design_2023)
head(coef(fit_2023))

contrast.matrix_2023 <- makeContrasts(F - M,
                                 levels=colnames(coef(fit_2023)))
fits_2023 <- contrasts.fit(fit_2023, contrast.matrix_2023)
ebFit_2023 <- eBayes(fits_2023)

myTopHits_2023 <- topTable(ebFit_2023, adjust ="BH", coef=1, number=500000, sort.by="logFC")
myTopHits_2023.df <- myTopHits_2023 %>%
  as_tibble(rownames = "geneID")
write_tsv(myTopHits_2023.df,"2024_09_03_myTopHits_2023.txt")

results_2023 <- decideTests(ebFit_2023, method="global", adjust.method="BH", adjusted.p.value=0.01, lfc=2)
head(results_2023)
summary(results_2023) # counts up -1, 0 and 1s 

colnames(v.DEGList_2023.filtered.norm$E) <- sampleID_2023
diffGenes_2023 <- v.DEGList_2023.filtered.norm$E[results_2023[,1] !=0,]
diffGenes_2023.df <- as_tibble(diffGenes_2023, rownames = "geneID")
write_tsv(diffGenes_2023.df,"2024_09_03_DiffGenes_2023.txt") #NOTE: this .txt file can be directly used for input into other clustering or network analysis tools (e.g., String, Clust (https://github.com/BaselAbujamous/clust, etc.)


###### 2022

myCounts_2022 <- Txi_gene_2022$counts
myDGEList_2022 <- DGEList(counts=myCounts_2022, group = factor(sex_2022))
cpm <- cpm(myDGEList_2022) 
keepers <- rowSums(cpm>1)>=5
myDGEList_2022.filtered<- myDGEList_2022[keepers,]
myDGEList_2022.filtered.norm <- calcNormFactors(myDGEList_2022.filtered, method = "TMM")


group_2022 <- factor(c("F", "F", "F", "F", "F", "F",
                      "M", "M", "M", "M", "M", "M"))

design_2022 <- model.matrix(~0 + group_2022)
colnames(design_2022) <- gsub("group_2022", "", colnames(design_2022))
v.DEGList_2022.filtered.norm <- voom(myDGEList_2022.filtered.norm, design_2022, plot = TRUE)
fit_2022 <- lmFit(v.DEGList_2022.filtered.norm, design_2022)
head(coef(fit_2022))

contrast.matrix_2022 <- makeContrasts(F - M,
                                      levels=colnames(coef(fit_2022)))
fits_2022 <- contrasts.fit(fit_2022, contrast.matrix_2022)
ebFit_2022 <- eBayes(fits_2022)
myTopHits_2022 <- topTable(ebFit_2022, adjust ="BH", coef=1, number=500000, sort.by="logFC")
myTopHits_2022.df <- myTopHits_2022 %>%
  as_tibble(rownames = "geneID")
write_tsv(myTopHits_2022.df,"2024_09_03_myTopHits_2022.txt")

results_2022 <- decideTests(ebFit_2022, method="global", adjust.method="BH", adjusted.p.value=0.01, lfc=2)
head(results_2022)
summary(results_2022) # counts up -1, 0 and 1s 

colnames(v.DEGList_2022.filtered.norm$E) <- sampleID_2022
diffGenes_2022 <- v.DEGList_2022.filtered.norm$E[results_2022[,1] !=0,]
diffGenes_2022.df <- as_tibble(diffGenes_2022, rownames = "geneID")
write_tsv(diffGenes_2022.df,"2024_09_03_DiffGenes_2022.txt") #NOTE: this .txt file can be directly used for input into other clustering or network analysis tools (e.g., String, Clust (https://github.com/BaselAbujamous/clust, etc.)

###### 2021

myCounts_2021 <- Txi_gene_2021$counts
myDGEList_2021 <- DGEList(counts=myCounts_2021, group = factor(sex_2021))
cpm <- cpm(myDGEList_2021) 
keepers <- rowSums(cpm>1)>=5
myDGEList_2021.filtered<- myDGEList_2021[keepers,]
myDGEList_2021.filtered.norm <- calcNormFactors(myDGEList_2021.filtered, method = "TMM")


group_2021 <- factor(c("F", "F", "F", "F", "F",
                      "M", "M", "M", "M"))

design_2021 <- model.matrix(~0 + group_2021)
colnames(design_2021) <- gsub("group_2021", "", colnames(design_2021))
v.DEGList_2021.filtered.norm <- voom(myDGEList_2021.filtered.norm, design_2021, plot = TRUE)
fit_2021 <- lmFit(v.DEGList_2021.filtered.norm, design_2021)
head(coef(fit_2021))

contrast.matrix_2021 <- makeContrasts(F - M,
                                      levels=colnames(coef(fit_2021)))
fits_2021 <- contrasts.fit(fit_2021, contrast.matrix_2021)
ebFit_2021 <- eBayes(fits_2021)

myTopHits_2021 <- topTable(ebFit_2021, adjust ="BH", coef=1, number=500000, sort.by="logFC")
myTopHits_2021.df <- myTopHits_2021 %>%
  as_tibble(rownames = "geneID")
write_tsv(myTopHits_2021.df,"2024_09_03_myTopHits_2021.txt")

results_2021 <- decideTests(ebFit_2021, method="global", adjust.method="BH", adjusted.p.value=0.01, lfc=2)
head(results_2021)
summary(results_2021) # counts up -1, 0 and 1s 

colnames(v.DEGList_2021.filtered.norm$E) <- sampleID_2021
diffGenes_2021 <- v.DEGList_2021.filtered.norm$E[results_2021[,1] !=0,]
diffGenes_2021.df <- as_tibble(diffGenes_2021, rownames = "geneID")
write_tsv(diffGenes_2021.df,"2024_09_03_DiffGenes_2021.txt") #NOTE: this .txt file can be directly used for input into other clustering or network analysis tools (e.g., String, Clust (https://github.com/BaselAbujamous/clust, etc.)





#######Across Years ###########################
vol_2023 <- ggplot(myTopHits_2023.df) +
  aes(y=-log10(adj.P.Val), x=logFC, text = paste("Symbol:", geneID)) +
  geom_point(size=2, alpha=0.5) +
  # the cut-offs
  geom_hline(yintercept = -log10(0.01), linetype="longdash", colour="grey", linewidth=1) +
  geom_vline(xintercept = 2, linetype="longdash", colour="#40B0A6", size=1) +
  geom_vline(xintercept = -2, linetype="longdash", colour="#E1BE6A", size=1) +
  # To highlight where the genes are differentially expressed 
  annotate("rect", xmin = 2, xmax = 20, ymin = -log10(0.01), ymax = 16, alpha=.2, fill="#40B0A6") +
  annotate("rect", xmin = -2, xmax = -20, ymin = -log10(0.01), ymax = 16, alpha=.2, fill="#E1BE6A") +
  # annotate(geom="text",x=-12, y=5, label="Male", size=5) +
  # annotate(geom="text",x=12, y=5, label="Female", size=5) +
  theme_bw()

vol_2022 <-ggplot(myTopHits_2022.df) +
  aes(y=-log10(adj.P.Val), x=logFC, text = paste("Symbol:", geneID)) +
  geom_point(size=2, alpha=0.5) +
  # the cut-offs
  geom_hline(yintercept = -log10(0.01), linetype="longdash", colour="grey", linewidth=1) +
  geom_vline(xintercept = 2, linetype="longdash", colour="#40B0A6", size=1) +
  geom_vline(xintercept = -2, linetype="longdash", colour="#E1BE6A", size=1) +
  # To highlight where the genes are differentially expressed 
  annotate("rect", xmin = 2, xmax = 20, ymin = -log10(0.01), ymax = 16, alpha=.2, fill="#40B0A6") +
  annotate("rect", xmin = -2, xmax = -20, ymin = -log10(0.01), ymax = 16, alpha=.2, fill="#E1BE6A") +
  # annotate(geom="text",x=-12, y=5, label="Male", size=5) +
  # annotate(geom="text",x=12, y=5, label="Female", size=5) +
  theme_bw()

vol_2021 <- ggplot(myTopHits_2021.df) +
  aes(y=-log10(adj.P.Val), x=logFC, text = paste("Symbol:", geneID)) +
  geom_point(size=2, alpha=0.5) +
  # the cut-offs
  geom_hline(yintercept = -log10(0.01), linetype="longdash", colour="grey", linewidth=1) +
  geom_vline(xintercept = 2, linetype="longdash", colour="#40B0A6", size=1) +
  geom_vline(xintercept = -2, linetype="longdash", colour="#E1BE6A", size=1) +
  # To highlight where the genes are differentially expressed 
  annotate("rect", xmin = 2, xmax = 20, ymin = -log10(0.01), ymax = 16, alpha=.2, fill="#40B0A6") +
  annotate("rect", xmin = -2, xmax = -20, ymin = -log10(0.01), ymax = 16, alpha=.2, fill="#E1BE6A") +
  # annotate(geom="text",x=-12, y=5, label="Male", size=5) +
  # annotate(geom="text",x=12, y=5, label="Female", size=5) +
  theme_bw()

library(Rmisc)
setwd("C:/Users/vl29/OneDrive - University of St Andrews/Desktop/RitchieLab/KitchenFlies/Code/rnaseq/")
pdf(file="./Figures/2024_09/2024_09_03_volcano_acrossyears_noM14M18.pdf", width=14, height=4, onefile=TRUE)
par(mfrow=c(1,3))
multiplot(vol_2021, vol_2022, vol_2023, cols=3)
dev.off()

# recall that abundance data are TPM, while the counts are read counts mapping to each gene or transcript

###############################################################
#### For everyone 
###############################################################
myTPM <- Txi_gene$abundance # if you make it with transcripts, its far larger
myCounts <- Txi_gene$counts

# capture sample labels from the study design file that you worked with and saved as 'df' in step 1
sampleID <- df$sampleID

# Generate summary stats for your data ----
myTPM.stats <- transform(myTPM, 
                         SD=rowSds(myTPM), 
                         AVG=rowMeans(myTPM),
                         MED=rowMedians(myTPM))


myCounts.stats <- transform(myCounts, 
                            SD=rowSds(myCounts), 
                            AVG=rowMeans(myCounts),
                            MED=rowMedians(myCounts))


write.csv(myTPM.stats, "2024_08/TPM_stats.csv")
write.csv(myCounts.stats, "2024_08/counts_stats.csv")

tiff("./Figures/2023_12_01_TPMstats.tiff", units="in", width=4, height=3, res=300)
ggplot(myTPM.stats) + 
  aes(x = SD, y = MED) +
  geom_point(size=1, alpha = 2/10) +
  #geom_smooth(method=lm) +
  labs(y="Median", x = "Standard Deviation") +
  #title="Transcripts per million (TPM)",
  #subtitle="unfiltered, non-normalized data") +
  theme_bw()
dev.off()

# Look at correlation 
myCounts <-data.frame(myCounts)
myCounts  <- tibble::rownames_to_column(myCounts, "Gene")
colnames(myCounts) <- c("Gene","F3", "F5", "F6", "F7", "F8", 
                        "M18", "M3", "M4", "M5", "M6",
                        "DmF11", "DmF12", "DmF13", "DmF14", "DmF15", "DmF16",
                        "DmM20", "DmM21", "DmM22", "DmM23", "DmM24", "DmM25",
                        "Dm_F10", "Dm_F5", "Dm_F6", "Dm_F8", "Dm_F9",
                        "Dm_M12", "Dm_M13", "Dm_M14", "Dm_M15", "Dm_M17")
long_myCounts <- myCounts %>% 
  pivot_longer(
    cols=-Gene,
    names_to = "Sample",
    values_to = "Count")

myCounts_corr <- myCounts %>%
  dplyr::select(-Gene) %>%
  cor(method="spearman")

pdf(file="./Figures/2024_08/2024_08_12_corr.pdf", width=8, height=7, onefile = TRUE)
par(mfrow=c(1,1),
    mar=c(4, 4, 3, 4),
    xpd=TRUE)

corrplot <- corrplot(myCounts_corr, 
                     #cl.lim=c(0,1),
                     is.corr=FALSE,
                     method = "color", 
                     type="upper", 
                     diag=FALSE,
                     col = COL1('YlOrRd', 10),
                     tl.col = 'black')
dev.off()

###############################
#####--Using Edge R ############
################################

sex <- c("F", "F", "F", "F", "F", 
         "M", "M", "M", "M", "M",
         "F", "F", "F", "F", "F", "F",
         "M", "M", "M", "M", "M", "M",
         "F", "F", "F", "F", "F",
         "M", "M", "M", "M", "M")

year <- c("2023", "2023", "2023", "2023", "2023", 
          "2023", "2023", "2023", "2023", "2023",
          "2022", "2022", "2022", "2022", "2022", "2022", 
          "2022", "2022", "2022", "2022", "2022", "2022",
          "2021", "2021", "2021", "2021", "2021",
          "2021", "2021", "2021", "2021", "2021")

# Make a DGElist from your counts - limma, edgeR, all wants to work with raw counts
myDGEList <- DGEList(counts=myCounts, group = factor(sex))

#DEGList objects are a good R data file to consider saving to you working directory
save(myDGEList, file = "Data/2024_08/2024_08_12_myDGEList") # load(file = "myDGEList")

# Get counts per million
cpm <- cpm(myDGEList) 
log2.cpm <- cpm(myDGEList, log=TRUE)


L <- mean(myDGEList$samples$lib.size) * 1e-6
M <- median(myDGEList$samples$lib.size) * 1e-6
c(L, M)

# Explore the data (logged so you can see it better!)
log2.cpm.df <- as_tibble(log2.cpm, rownames = "geneID")
colnames(log2.cpm.df) <- c("geneID", as.character(sampleID)) # add sample names 

log2.cpm.df_pivot <- pivot_longer(log2.cpm.df, # dataframe to be pivoted
                                  cols = sampleID[1:32], # column names to be stored as a SINGLE variable
                                  names_to = "samples", # name of that new variable (column)
                                  values_to = "expression") # name of new variable (column) storing all the values (data)

tiff("./Figures/2023_11_30_log2CPM_unfiltered_nonorm.tiff", units="in", width=10, height=5, res=300)
ggplot(log2.cpm.df_pivot) +
  aes(x=samples, y=expression, fill=samples) +
  geom_violin(trim = FALSE, show.legend = FALSE) +
  scale_fill_viridis_d() +
  stat_summary(fun = "median", 
               geom = "point", 
               shape = 95, 
               size = 10, 
               color = "black", 
               show.legend = FALSE) +  
  labs(x="Sample ID",
       y="Log2 Counts per Million (CPM)") +
  #title="Log2 Counts per Million (CPM)",
  #subtitle="unfiltered, non-normalized") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90))
dev.off()

################################################################ 
####################### Filter your data #######################
################################################################
table(rowSums(myDGEList$counts==0)==10) # how many genes or transcripts have no read counts

# counts per million, greater than one, in groups of 10 (per batch)
keepers <- rowSums(cpm>1)>=5
myDGEList.filtered <- myDGEList[keepers,]
dim(myDGEList.filtered)

# Explore your filtered dataset
cpm.filtered <- cpm(myDGEList.filtered, log=TRUE)
cpm.filtered.df <- as_tibble(cpm.filtered, rownames = "geneID")
colnames(cpm.filtered.df) <- c("geneID", as.character(sampleID))

cpm.filtered.df_pivot <- pivot_longer(cpm.filtered.df, # dataframe to be pivoted
                                      cols = sampleID[1:32], # column names to be stored as a SINGLE variable
                                      names_to = "samples", # name of that new variable (column)
                                      values_to = "expression") # name of new variable (column) storing all the values (data)

pdf(file="./Figures/2024_08/2024_08_12_CPM_filtered_nonorm.pdf", width=10, height=5, onefile = TRUE)
par(mfrow=c(1,1),
    mar=c(4, 4, 3, 4),
    xpd=TRUE)

ggplot(cpm.filtered.df_pivot) +
  aes(x=samples, y=expression, fill=samples) +
  geom_violin(trim = FALSE, show.legend = FALSE) +
  scale_fill_viridis_d() +
  stat_summary(fun = "median", 
               geom = "point", 
               shape = 95, 
               size = 8, 
               color = "black", 
               show.legend = FALSE) +
  labs(x="Sample ID", y="Log2 Counts per Million (CPM)") +
  #title="Log2 Counts per Million (CPM)",
  #subtitle="filtered, non-normalized")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90))
dev.off()

################################################################ 
################ Normalize data between samples ################ 
################################################################

myDGEList.filtered.norm <- calcNormFactors(myDGEList.filtered, method = "TMM")

# Explore your data again 
cpm.filtered.norm <- cpm(myDGEList.filtered.norm)
cpm.filtered.norm.log <- cpm(myDGEList.filtered.norm, log=TRUE)
cpm.filtered.norm.log.df <- as_tibble(cpm.filtered.norm.log, rownames = "geneID")
colnames(cpm.filtered.norm.log.df) <- c("geneID", as.character(sampleID))

cpm.filtered.norm.log.df_pivot <- pivot_longer(cpm.filtered.norm.log.df, # dataframe to be pivoted
                                               cols = sampleID[1:32], # column names to be stored as a SINGLE variable
                                               names_to = "samples", # name of that new variable (column)
                                               values_to = "expression") # name of new variable (column) storing all the values (data)

pdf(file="./Figures/2024_08/2024_08_12_CPM_filtered_norm.pdf", width=10, height=5, onefile = TRUE)
par(mfrow=c(1,1),
    mar=c(4, 4, 3, 4),
    xpd=TRUE)

ggplot(cpm.filtered.norm.log.df_pivot) +
  aes(x=samples, y=expression, fill=samples) +
  geom_violin(trim = FALSE, show.legend = FALSE) +
  scale_fill_viridis_d() +
  stat_summary(fun = "median",
               geom = "point",
               shape = 95,
               size = 8,
               color = "black",
               show.legend = FALSE) +
  labs(x="Sample ID", y="Log2 Counts per Million (CPM)")+
  #  title="Log2 Counts per Million (CPM)",
  # subtitle="filtered, TMM normalized") +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90))
dev.off()

################################################################ 
############## Hierarchical clustering #########################
################################################################ 
# In a matrix you can have the rownames not as a part of the actual matrix
# Calculates distance between rows, but we want the the distance between samples,
# not between genes! (t) 
distance_max <- dist(t(cpm.filtered.norm), method = "maximum") #other distance methods are "euclidean", maximum", "manhattan", "canberra", "binary" or "minkowski"
distance_eu <- dist(t(cpm.filtered.norm), method = "euclidean") #other distance methods are "euclidean", maximum", "manhattan", "canberra", "binary" or "minkowski"

clusters_am <- hclust(distance_max, method = "average") #other agglomeration methods are "ward.D", "ward.D2", "single", "complete", "average", "mcquitty", "median", or "centroid"
clusters_cm <- hclust(distance_max, method = "complete")
clusters_ae <- hclust(distance_eu, method = "average") 
clusters_ce <- hclust(distance_eu, method = "complete") 

pdf(file="./Figures/2024_08/2024_08_12_maxdist.pdf", width=10, height=7, onefile = TRUE)
par(mfrow=c(2,2),
    mar=c(4, 4, 3, 4),
    xpd=TRUE)

plot(clusters_am, labels=sampleID,main = "")
plot(clusters_cm, labels=sampleID,main = "")
plot(clusters_ae, labels=sampleID,main = "")
plot(clusters_ce, labels=sampleID,main = "")
dev.off()

# Structure is pretty different but its not radically changed...
# M14, M18... check they're quite far out -> check how many reads aligned 
# Maybe something is inherently wrong... but know this as its tracked through
# the analysis 

#########################################################################
############# Principal component analysis (PCA)#########################
###########################################################################
pca.res <- prcomp(t(cpm.filtered.norm), scale.=F, retx=T)

ls(pca.res) 

summary(pca.res) # Prints variance summary for all principal components.
# The proportion of variance is really taken by PC1 and PC2 and then drops
# off considerably 

pca.res$rotation #$rotation shows you how much each gene influenced each PC (called 'scores')
pca.res$x # 'x' shows you how much each sample influenced each PC (called 'loadings')
#note that these have a magnitude and a direction (this is the basis for making a PCA plot)

screeplot(pca.res) # A screeplot is a standard way to view eigenvalues for each PCA - variance account for
pc.var<-pca.res$sdev^2 # sdev^2 captures these eigenvalues from the PCA result
pc.per<-round(pc.var/sum(pc.var)*100, 1) # we can then use these eigenvalues to calculate the percentage variance explained by each PC
pc.per

# plot any two PCs against each other
pca.res.df <- as_tibble(pca.res$x)
tiff("./Figures/2024_06_03_pca_year.tiff", units="in", width=5, height=4, res=300)
ggplot(pca.res.df) +
  aes(x=PC1, y=PC2, color = year) +
  geom_point(size=2,alpha = 3/10) +
  stat_ellipse() +
  xlab(paste0("PC1 (",pc.per[1],"%",")")) + 
  ylab(paste0("PC2 (",pc.per[2],"%",")")) +
  theme_bw()
dev.off()

# Can use coord_fixed to fix them but when you use stat_elipse... by year, its not great. 

tiff("./Figures/2024_06_03_pca_sex.tiff", units="in", width=4, height=3, res=300)
ggplot(pca.res.df) +
  aes(x=PC1, y=PC2, label=factor(sampleID), color = sex) +
  geom_point(size=2,alpha = 2/10) +
  stat_ellipse() +
  xlab(paste0("PC1 (",pc.per[1],"%",")")) + 
  ylab(paste0("PC2 (",pc.per[2],"%",")")) +
  coord_fixed() +
  theme_bw()
dev.off()

tiff("./Figures/2024_06_03_pca_person.tiff", units="in", width=5, height=4, res=300)
ggplot(pca.res.df) +
  aes(x=PC1, y=PC2, label=factor(sampleID), color = person) +
  geom_point(size=2,alpha = 2/10) +
  stat_ellipse() +
  xlab(paste0("PC1 (",pc.per[1],"%",")")) + 
  ylab(paste0("PC2 (",pc.per[2],"%",")")) +
  theme_bw()
dev.off()

# PCA for all
a<-ggplot(pca.res.df) +
  aes(x=PC1, y=PC2, color = year) +
  geom_point(size=2,alpha = 3/10) +
  stat_ellipse() +
  xlab(paste0("PC1 (",pc.per[1],"%",")")) + 
  ylab(paste0("PC2 (",pc.per[2],"%",")")) +
  theme_bw()

b<-ggplot(pca.res.df) +
  aes(x=PC1, y=PC2, color = sex) +
  geom_point(size=2,alpha = 2/10) +
  stat_ellipse() +
  xlab(paste0("PC1 (",pc.per[1],"%",")")) + 
  ylab(paste0("PC2 (",pc.per[2],"%",")")) +
  coord_fixed() +
  theme_bw()

c<-ggplot(pca.res.df) +
  aes(x=PC1, y=PC2, color = person) +
  geom_point(size=2,alpha = 2/10) +
  stat_ellipse() +
  xlab(paste0("PC1 (",pc.per[1],"%",")")) + 
  ylab(paste0("PC2 (",pc.per[2],"%",")")) +
  theme_bw()

tiff("./Figures/2024_06_03_pca_all.tiff", units="in", width=8, height=7, res=300)
multiplot(a, b, c, cols=2)
dev.off()

###########################################################################
########################## Create a PCA 'small multiples' chart ----
###########################################################################
# view PCA loadings to understand impact of each sample on each pricipal component
pca.res.df <- pca.res$x[,1:4] %>% # note that this is the first time you've seen the 'pipe' operator from the magrittr package
  as_tibble() %>%
  add_column(sample = sampleID,
             sex = sex,
             year = year,
             person = person)

pca.pivot <- pivot_longer(pca.res.df, # dataframe to be pivoted
                          cols = PC1:PC4, # column names to be stored as a SINGLE variable
                          names_to = "PC", # name of that new variable (column)
                          values_to = "loadings") # name of new variable (column) storing all the values (data)

tiff("./Figures/2024_06_03_pca_sm_sex.tiff", units="in", width=10, height=8, res=300)
ggplot(pca.pivot) +
  aes(x=sample, y=loadings, fill=sex) + # you could iteratively 'paint' different covariates onto this plot using the 'fill' aes
  geom_bar(stat="identity") +
  facet_wrap(~PC) +
  theme_bw()+
  theme(strip.background=element_rect(colour="black", fill="white")) +
  coord_flip()
dev.off()

tiff("./Figures/2024_06_03_pca_sm_year.tiff", units="in", width=10, height=8, res=300)
ggplot(pca.pivot) +
  aes(x=sample, y=loadings, fill=year) + # you could iteratively 'paint' different covariates onto this plot using the 'fill' aes
  geom_bar(stat="identity") +
  facet_wrap(~PC) +
  theme_bw() +
  theme(strip.background=element_rect(colour="black",
                                      fill="white")) +
  coord_flip()
dev.off()

tiff("./Figures/2024_06_03_pca_sm_person.tiff", units="in", width=10, height=8, res=300)
ggplot(pca.pivot) +
  aes(x=sample, y=loadings, fill=person) + # you could iteratively 'paint' different covariates onto this plot using the 'fill' aes
  geom_bar(stat="identity") +
  facet_wrap(~PC) +
  theme_bw() +
  theme(strip.background=element_rect(colour="black",
                                      fill="white")) +
  coord_flip()
dev.off()

pdf(file="./Figures/2024_08/2024_08_12_mds.pdf", width=7, height=5, onefile = TRUE)
par(mfrow=c(1,1),
    mar=c(4, 4, 3, 4),
    xpd=TRUE)

plotMDS(myDGEList.filtered.norm, method="bcv", col=as.numeric(myDGEList.filtered.norm$samples$group), pch=16)
legend("bottomleft", c("Females", "Males"), col=1:2, pch=16)
dev.off()

# Modify our dataframe ----
# mydata.df <- cpm.filtered.norm.df %>%
#   mutate(m.AVG = (M18+M3+M4+M5+M6+DmM20+DmM21+DmM22+DmM23+DmM24+DmM25+Dm_M12+Dm_M13+Dm_M14+Dm_M15+Dm_M17)/16,
#          f.AVG = (F3+F5+F6+F7+F8+DmF11+DmF12+DmF13+DmF14+DmF15+DmF16+Dm_F10+Dm_F5+Dm_F6+Dm_F8+Dm_F9)/16,
#          #now make columns comparing each of the averages above that you're interested in
#          LogFC = (f.AVG - m.AVG)) %>%  # log-fold change and worked in a log scale, its -
#   mutate_if(is.numeric, round, 2)

# test <- estimateDisp(myDGEList.filtered.norm)
# et <- exactTest(test)
# result_edgeR <- as.data.frame(topTags(et, n=nrow(Txi_gene)))
# table(result_edgeR$FDR < 0.05)
# plot(result_edgeR$logFC, -log10(result_edgeR$FDR), col=ifelse(result_edgeR$FDR<0.05,"red","black"),main="FDR volcano plot",xlab="log2FC",ylab="-log10(FDR)")
# hist(result_edgeR$PValue, breaks=20, xlab="P-Value", col="royalblue", ylab="Frequency", main="P-value distribution")

group <- factor(c("F", "F", "F", "F", "F", 
                  "M", "M", "M", "M", "M",
                  "F", "F", "F", "F", "F", "F",
                  "M", "M", "M", "M", "M", "M",
                  "F", "F", "F", "F", "F",
                  "M", "M", "M", "M", "M"))

year <- factor(c("2023", "2023", "2023", "2023", "2023", 
                 "2023", "2023", "2023", "2023", "2023",
                 "2022", "2022", "2022", "2022", "2022", "2022", 
                 "2022", "2022", "2022", "2022", "2022", "2022",
                 "2021", "2021", "2021", "2021", "2021",
                 "2021", "2021", "2021", "2021", "2021"))


###########################################################################
################################ Modelling ################################
###########################################################################

# take a look at limma for this - all for experimental design
# means I want no intercept for model matrix and do comparisons 
# for sex
design <- model.matrix(~0 + group)

colnames(design) <- gsub("group", "", colnames(design))

# NOTE: if you need a paired analysis (a.k.a.'blocking' design) or have a batch effect, the following design is useful
# design2 <- model.matrix(~sex+year)
# colnames(design2) <- c("2021", "2022", "2023", "M")
# this is just an example. 'block' and 'treatment' would need to be objects in your environment

# However,PCA plot does not suggest a substantial batch/year effect.....

# Model mean-variance trend and fit linear model to data ----
# heteroskedatity- no matter what we do, RNAseq data will always
# have unequal variance across a range of increasing means of gene
# expression - try to deal with that by log conversion

# Use VOOM (Limma) to model the mean-variance relationship for each gene 
# variance stabilize the data, models it and applies precision weights
# depending on how it fits the data 

# when converted to log-2, lowly expressed genes have slightly higher variance
v.DEGList.filtered.norm <- voom(myDGEList.filtered.norm, design, plot = TRUE)


pdf(file="./Figures/2024_08/2024_08_12_voom.pdf", width=6, height=4, onefile = TRUE)
par(mfrow=c(1,1),
    mar=c(4, 4, 3, 4),
    xpd=TRUE)

v.DEGList.filtered.norm <- voom(myDGEList.filtered.norm, design, plot = TRUE)
dev.off()
# now there is a new element called weights, which are precision weights applied to each gene
# in each sample (each column) that help to use the mean-variance trend to improve ability 
# to detect differently expressed genes 
# fit a linear model to your data
fit <- lmFit(v.DEGList.filtered.norm, design)
head(coef(fit))

# Contrast matrix - pairwise comparisons
contrast.matrix <- makeContrasts(F - M,
                                 levels=colnames(coef(fit)))

# extract the linear model fit
fits <- contrasts.fit(fit, contrast.matrix)

#get bayesian stats for your linear model fit
ebFit <- eBayes(fits)

pdf(file="./Figures/2024_08/2024_08_12_ebFit.pdf", width=6, height=4, onefile = TRUE)
par(mfrow=c(1,1),
    mar=c(4, 4, 3, 4))

plotSA(ebFit, main="Final model: Mean-variance trend")
dev.off()

write.fit(ebFit, file="2023_11_24_lmfit_results.txt")

tfit<-treat(fit,lfc=1)
dt<-decideTests(tfit)
vennDiagram(dt[,1:2], circle.col=c("turquoise", "salmon"))

myTopHits <- topTable(ebFit, adjust ="BH", coef=1, number=40000, sort.by="logFC")
myTopHits.df <- myTopHits %>%
  as_tibble(rownames = "geneID")

length(which(myTopHits$adj.P.Val < 0.05))
# look at them in you're interest (maybe just a sub-section)
# gt(myTopHits.df)

# TopTable (from Limma) outputs a few different stats:
# logFC, AveExpr, and P.Value should be self-explanatory
# adj.P.Val is your adjusted P value, also known as an FDR (if BH method was used for multiple testing correction)

# B statistic is the log-odds that that gene is differentially expressed. 
# If B = 1.5, then log odds is e^1.5, where e is euler's constant (approx. 2.718).  
# So, the odds of differential expression os about 4.8 to 1
# t statistic is ratio of the logFC to the standard error 
# (where the error has been moderated across all genes...
# because of Bayesian approach)

# Volcano Plots ----
# in topTable function above, set 'number=40000' to capture all genes

# now plot
tiff("./Figures/2024_06_03_volcano.tiff", units="in", width=8, height=5, res=300)
ggplot(myTopHits.df) +
  aes(y=-log10(adj.P.Val), x=logFC, text = paste("Symbol:", geneID)) +
  geom_point(size=2, alpha=0.5) +
  # the cut-offs
  geom_hline(yintercept = -log10(0.01), linetype="longdash", colour="grey", linewidth=1) +
  geom_vline(xintercept = 1, linetype="longdash", colour="#40B0A6", size=1) +
  geom_vline(xintercept = -1, linetype="longdash", colour="#E1BE6A", size=1) +
  # To highlight where the genes are differentially expressed 
  annotate("rect", xmin = 1, xmax = 15, ymin = -log10(0.01), ymax = 34, alpha=.2, fill="#40B0A6") +
  annotate("rect", xmin = -1, xmax = -18.5, ymin = -log10(0.01), ymax = 34, alpha=.2, fill="#E1BE6A") +
  # annotate(geom="text",x=-12, y=5, label="Male", size=5) +
  # annotate(geom="text",x=12, y=5, label="Female", size=5) +
  theme_bw()
dev.off()
# Now make the volcano plot above interactive with plotly
ggplotly(vplot)

# Things to the right (positive) are much higher in females, things 
# to the left are much higher in males (negative)

# Also we transformed the value to make it inverse log 10, those with low adjusted p values now
# appear very high up - this helps us understand magnitude of change on x axis and significance
# on y for any pairwise comparison 

# decideTests to pull out the DEGs that make the cut-off criteria
# like, where do you draw the line? and make Venn Diagram ----
results <- decideTests(ebFit, method="global", adjust.method="BH", p.value=0.01, lfc=2)

head(results)
summary(results) # counts up -1, 0 and 1s 
vennDiagram(results, include="up")
vennDiagram(results, include="down")
vennDiagram(results, include ="both")
vennDiagram(results, 
            include=c("up", "down"),
            counts.col=c("red", "blue"))
# circle.col = c("red", "blue", "green3"))



# retrieve expression data for your DEGs 
colnames(v.DEGList.filtered.norm$E) <- sampleID

# Only want the rows where results in the (decide tests table) is not zero
diffGenes <- v.DEGList.filtered.norm$E[results[,1] !=0,]

#convert your DEGs to a dataframe using as_tibble
diffGenes.df <- as_tibble(diffGenes, rownames = "geneID")

write_tsv(diffGenes.df,"2023_11_24_DiffGenes.txt") #NOTE: this .txt file can be directly used for input into other clustering or network analysis tools (e.g., String, Clust (https://github.com/BaselAbujamous/clust, etc.)
